name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Sagar"
      - name: 'Sending SMS Notification'
        uses: sagarchoudhary96/exosms-actions@v1
        with:
          fromNumber: '+918047193542'
          toNumber: '+919056455979'
          message: 'New Code Changes to master'
        env:
          EXOTEL_ACCOUNT_SID: ${{ secrets.EXOTEL_ACCOUNT_SID }}
          EXOTEL_API_KEY: ${{ secrets.EXOTEL_API_KEY }}
          EXOTEL_API_TOKEN: ${{ secrets.EXOTEL_API_TOKEN }}